# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - targets:
      - go_118_first_class
      - android_arm64
      - android_amd64
      - freebsd_amd64
      - freebsd_arm64
      - freebsd_386
      - windows_arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: binary
    format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
